### ISSUE TITLE
links to url(…) in css can be broken

### ISSUE THREAD

**Issue by Fil** [0gust1/cli-html-smoosher#7]
typically when in css/sheet.css you have 

```
.search:after {
    content: url("icon/search.png");
}
```

the path should be made relative to the new css localtion, which is the html content

**Comment by 0gust1** [comment]
Hi Fil,

I'll look into that. I think I have to make a function to reprocess the CSS content, with the base URL as a parameter.

Could you detail how you use the tool ? Basically, it does not care about images (in HTML or CSS), so I guess you use it with another tools in the chain ?

**Comment by Fil** [comment]
I have:
```
maps/map.html
css/styles.css
```

and I do `smoosh http://localhost/maps/map.html > map/index.html`

(But I've solved my problem by specifying `url(../css/icon/search.png)`)

**Comment by 0gust1** [comment]
map.html ? cartography ? ;)

Feel free to reopen the issue or suggest other things (You seems to be the only user and user is king ^^).
